### ISSUE TITLE
Cartalyst Sentinel support

### ISSUE THREAD

**Issue by mikemand** [Cannonb4ll/LaraBug#1]
Hello,

Would it be possible to support getting the user from Sentinel instead of Laravel's auth?

Thank you!

**Comment by Cannonb4ll** [comment]
Hello Mike,

That  should not be a problem, are you refering to this package? https://cartalyst.com/manual/sentinel/2.0

**Comment by mikemand** [comment]
Hello Dennis,

Yes, that is the correct package. I notice this is where you get the user: https://github.com/Cannonb4ll/LaraBug/blob/master/src/Helpers/Logger.php#L47

I would PR it myself, but I am unsure of your rules and guidelines for contributing.

Thank you!

**Comment by Cannonb4ll** [comment]
Mike,

Thats correct, the user is passed that way. I am open for a PR any day, I have no actual rules or guidelines for this. :)
